// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfR2jcDykeAHcJ_lj0qNJp3KeDB2OlzjA',
    appId: '1:619311802725:android:ba91597558ebc98da8998c',
    messagingSenderId: '619311802725',
    projectId: 'calback-fdeeb',
    storageBucket: 'calback-fdeeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMFQpojC0v_h7LwRQoDYpuwklg2UkWJ-0',
    appId: '1:619311802725:ios:c56d5bf3216f248fa8998c',
    messagingSenderId: '619311802725',
    projectId: 'calback-fdeeb',
    storageBucket: 'calback-fdeeb.appspot.com',
    androidClientId: '619311802725-e14jlsdlfeg1psln8jbmh7fmpqlp88ov.apps.googleusercontent.com',
    iosClientId: '619311802725-6tbq7kftev6bs5ammv94gdtqanlldbo5.apps.googleusercontent.com',
    iosBundleId: 'com.calback.hym',
  );
}
