// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'falseapiKeyfordummyuseabcd12345',
    appId: 'falseapiKeyfordummyuseabcd12345',
    messagingSenderId: 'falseapiKeyfordummyuseabcd12345',
    projectId: 'falseapiKeyfordummyuseabcd12345',
    storageBucket: 'cfalseapiKeyfordummyuseabcd12345',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'falseapiKeyfordummyuseabcd123450',
    appId: '1falseapiKeyfordummyuseabcd12345c',
    messagingSenderId: 'falseapiKeyfordummyuseabcd12345725',
    projectId: 'falseapiKeyfordummyuseabcd12345alseapiKeyfordummyuseabcd12345eb',
    storageBucket: 'calbfalseapiKeyfordummyuseabcd12345m',
    androidClientId: 'falseapiKeyfordummyuseabcd12345',
    iosClientId: 'falseapiKeyfordummyuseabcd12345',
    iosBundleId: 'falseapiKeyfordummyuseabcd12345',
  );
}
